### ISSUE TITLE
AttributeError: 'StanfordTopo' object has no attribute 'add_switch'

### ISSUE THREAD

**Issue by dragonxtek** [Br1an6/Improvisation-of-Netplumber#3]
I'm tring to run mininet_builder.py
I have the following issue:
```bash
~ sudo ./mininet_builder.py 
Put Stanford backbone in Mininet
Starting with primary controller localhost:6633
Starting with dummy controller localhost:6633
Traceback (most recent call last):
  File "./mininet_builder.py", line 222, in <module>
    StanfordTopoTest(gethostbyname(args.controller_name), args.controller_port, gethostbyname(args.dummy_controller_name), args.dummy_controller_port)
  File "./mininet_builder.py", line 168, in StanfordTopoTest
    topo = StanfordTopo()
  File "./mininet_builder.py", line 61, in __init__
    self.add_switch( "s%s" % s )
AttributeError: 'StanfordTopo' object has no attribute 'add_switch'
```
Are you using an older version of mininet? I have version 2.3.0d1
Were you using an older version for some particular reason?

**Comment by Br1an6** [comment]
Yes, at that time I was using the older version. I'm still working on it. Will fix it and push it.
